### ISSUE TITLE
Switch to Server Side Rendering

### ISSUE THREAD

**Issue by alexdovzhanyn** [ElixiumNetwork/website#2]
Much better for SEO

**Comment by KamilStaszewski** [comment]
What technology you want to use for ssr?

**Comment by alexdovzhanyn** [comment]
@KamilStaszewski we want to keep it in react, just want to enable server side rendering with express as a backend. This'll help improve out SEO, and is the last thing we need to do before the website is "done". 

We're currently using create-react-app so ssr might be a bit annoying to implement

**Comment by KamilStaszewski** [comment]
I would love to, but i don't think im good enough. I will try though.

**Comment by alexdovzhanyn** [comment]
I'm sure ya are! There are plenty of examples on Google. Give it a try, and
feel free to ping me if you need help.

**Comment by edisonaugusthy** [comment]
@alexdovzhanyn  what about switching to nextjs...?

**Comment by alexdovzhanyn** [comment]
@edisonaugusthy I've personally never worked with it but if you want to open a PR that accomplishes the goal using Nextjs, I'm open to it
